"""Original url is not unique

Revision ID: 4e82239d0b0c
Revises: fd6d9cd7ea53
Create Date: 2026-03-12 23:15:50.729492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e82239d0b0c'
down_revision: Union[str, Sequence[str], None] = 'fd6d9cd7ea53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('short_links_original_url_key'), 'short_links', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('short_links_original_url_key'), 'short_links', ['original_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
