"""Link expiration added

Revision ID: 95fdebbcd569
Revises: 4e82239d0b0c
Create Date: 2026-03-13 14:27:12.908197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fdebbcd569'
down_revision: Union[str, Sequence[str], None] = '4e82239d0b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_links', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_links', 'expires_at')
    # ### end Alembic commands ###
