"""User - link relationship

Revision ID: fd6d9cd7ea53
Revises: 05f931cdb0d2
Create Date: 2026-03-12 22:50:30.521039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6d9cd7ea53'
down_revision: Union[str, Sequence[str], None] = '05f931cdb0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_links', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'short_links', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_links', type_='foreignkey')
    op.drop_column('short_links', 'owner_id')
    # ### end Alembic commands ###
